// Planned SEO short-URL redirects — generated from url-mapping.csv

export const seoShortUrlRedirects = [
  // ── /banners/* ──
  { source: "/banners/adjustable-telescopic-backdrop", destination: "/shop/banners-displays/backdrops-popups", permanent: true },
  { source: "/banners/custom-tent-10x10", destination: "/shop/banners-displays/tents-outdoor", permanent: true },
  { source: "/banners/double-sided-banners", destination: "/shop/banners-displays/vinyl-banners", permanent: true },
  { source: "/banners/fabric-pop-up-display", destination: "/shop/banners-displays/backdrops-popups", permanent: true },
  { source: "/banners/feather-flags", destination: "/shop/banners-displays/flags-hardware", permanent: true },
  { source: "/banners/mesh-banners", destination: "/shop/banners-displays/mesh-banners", permanent: true },
  { source: "/banners/pole-banners", destination: "/shop/banners-displays/pole-banners", permanent: true },
  { source: "/banners/retractable-banners", destination: "/shop/banners-displays/retractable-stands", permanent: true },
  { source: "/banners/step-repeat-backdrops", destination: "/shop/banners-displays/backdrops-popups", permanent: true },
  { source: "/banners/table-cloths", destination: "/shop/banners-displays/tabletop-displays", permanent: true },
  { source: "/banners/tabletop-banners", destination: "/shop/banners-displays/tabletop-displays", permanent: true },
  { source: "/banners/teardrop-flags", destination: "/shop/banners-displays/flags-hardware", permanent: true },
  { source: "/banners/vinyl-banners", destination: "/shop/banners-displays/vinyl-banners", permanent: true },
  { source: "/banners/x-banners", destination: "/shop/banners-displays/x-banner-stands", permanent: true },
  // ── /canvas/* ──
  { source: "/canvas/canvas-collages", destination: "/shop/canvas-prints/canvas-collages", permanent: true },
  { source: "/canvas/classic-canvas-prints", destination: "/shop/canvas-prints/classic-canvas-prints", permanent: true },
  { source: "/canvas/floating-frame-canvas", destination: "/shop/canvas-prints/floating-frame-canvas", permanent: true },
  { source: "/canvas/hex-canvas-prints", destination: "/shop/canvas-prints/hex-canvas-prints", permanent: true },
  { source: "/canvas/large-format-canvas", destination: "/shop/canvas-prints/large-format-canvas", permanent: true },
  { source: "/canvas/rolled-canvas-prints", destination: "/shop/canvas-prints/rolled-canvas-prints", permanent: true },
  { source: "/canvas/triptych-canvas-split", destination: "/shop/canvas-prints/triptych-canvas-split", permanent: true },
  // ── /print/* ──
  { source: "/print/booklets", destination: "/shop/marketing-business-print/booklets", permanent: true },
  { source: "/print/bookmarks", destination: "/shop/marketing-business-print/bookmarks", permanent: true },
  { source: "/print/brochures", destination: "/shop/marketing-business-print/brochures", permanent: true },
  { source: "/print/business-card-magnets", destination: "/shop/marketing-business-print/business-cards", permanent: true },
  { source: "/print/business-cards", destination: "/shop/marketing-business-print/business-cards", permanent: true },
  { source: "/print/calendars", destination: "/shop/marketing-business-print/calendars", permanent: true },
  { source: "/print/certificates", destination: "/shop/marketing-business-print/certificates", permanent: true },
  { source: "/print/document-printing", destination: "/shop/marketing-business-print/document-printing", permanent: true },
  { source: "/print/door-hangers", destination: "/shop/marketing-business-print/door-hangers", permanent: true },
  { source: "/print/envelopes", destination: "/shop/marketing-business-print/envelopes", permanent: true },
  { source: "/print/flyers", destination: "/shop/marketing-business-print/flyers", permanent: true },
  { source: "/print/greeting-invitation-cards", destination: "/shop/marketing-business-print/greeting-invitation-cards", permanent: true },
  { source: "/print/letterheads", destination: "/shop/marketing-business-print/letterhead", permanent: true },
  { source: "/print/menus", destination: "/shop/marketing-business-print/menus", permanent: true },
  { source: "/print/ncr-forms", destination: "/shop/marketing-business-print/ncr-forms", permanent: true },
  { source: "/print/notepads", destination: "/shop/marketing-business-print/notepads", permanent: true },
  { source: "/print/postcards", destination: "/shop/marketing-business-print/postcards", permanent: true },
  { source: "/print/posters", destination: "/shop/marketing-business-print/posters", permanent: true },
  { source: "/print/rack-cards", destination: "/shop/marketing-business-print/rack-cards", permanent: true },
  { source: "/print/table-tents", destination: "/shop/marketing-business-print/table-tents", permanent: true },
  { source: "/print/tickets-coupons", destination: "/shop/marketing-business-print/tickets-coupons", permanent: true },
  // ── /signs/* ──
  { source: "/signs/a-frame-signs", destination: "/shop/signs-rigid-boards/a-frame-sign-stand", permanent: true },
  { source: "/signs/directional-signs", destination: "/shop/signs-rigid-boards/directional-signs", permanent: true },
  { source: "/signs/election-signs", destination: "/shop/signs-rigid-boards/election-signs", permanent: true },
  { source: "/signs/event-photo-boards", destination: "/shop/signs-rigid-boards/selfie-frame-board", permanent: true },
  { source: "/signs/event-welcome-signs", destination: "/shop/signs-rigid-boards/welcome-sign-board", permanent: true },
  { source: "/signs/h-wire-stakes", destination: "/shop/signs-rigid-boards/h-stakes", permanent: true },
  { source: "/signs/open-house-signs", destination: "/shop/signs-rigid-boards/open-house-signs", permanent: true },
  { source: "/signs/presentation-boards", destination: "/shop/signs-rigid-boards/tri-fold-presentation-board", permanent: true },
  { source: "/signs/pvc-board-signs", destination: "/shop/signs-rigid-boards/pvc-board-signs", permanent: true },
  { source: "/signs/real-estate-sign-frames", destination: "/shop/signs-rigid-boards/real-estate-frame", permanent: true },
  { source: "/signs/real-estate-signs", destination: "/shop/signs-rigid-boards/real-estate-sign", permanent: true },
  { source: "/signs/yard-signs", destination: "/shop/signs-rigid-boards/yard-sign", permanent: true },
  // ── /stickers/* ──
  { source: "/stickers/asset-equipment-labels", destination: "/shop/stickers-labels-decals/asset-equipment-tags", permanent: true },
  { source: "/stickers/die-cut-stickers", destination: "/shop/stickers-labels-decals/die-cut-stickers", permanent: true },
  { source: "/stickers/electrical-chemical-labels", destination: "/shop/stickers-labels-decals/electrical-chemical", permanent: true },
  { source: "/stickers/hazard-warning-labels", destination: "/shop/stickers-labels-decals/hazard-warning", permanent: true },
  { source: "/stickers/kiss-cut-stickers", destination: "/shop/stickers-labels-decals/kiss-cut-singles", permanent: true },
  { source: "/stickers/pipe-valve-labels", destination: "/shop/stickers-labels-decals/pipe-valve-labels", permanent: true },
  { source: "/stickers/ppe-equipment-labels", destination: "/shop/stickers-labels-decals/ppe-equipment", permanent: true },
  { source: "/stickers/roll-labels", destination: "/shop/stickers-labels-decals/sticker-rolls", permanent: true },
  { source: "/stickers/safety-emergency-labels", destination: "/shop/stickers-labels-decals/fire-emergency", permanent: true },
  { source: "/stickers/sticker-sheets", destination: "/shop/stickers-labels-decals/sticker-pages", permanent: true },
  { source: "/stickers/warehouse-labels", destination: "/shop/stickers-labels-decals/warehouse-labels", permanent: true },
  // ── /surface-graphics/* ──
  { source: "/surface-graphics/blockout-window-vinyl", destination: "/shop/windows-walls-floors/blockout-vinyl", permanent: true },
  { source: "/surface-graphics/floor-graphics", destination: "/shop/windows-walls-floors/floor-graphics", permanent: true },
  { source: "/surface-graphics/frosted-privacy-film", destination: "/shop/windows-walls-floors/frosted-window-film", permanent: true },
  { source: "/surface-graphics/glass-waistline-stripes", destination: "/shop/windows-walls-floors/glass-waistline", permanent: true },
  { source: "/surface-graphics/one-way-vision-film", destination: "/shop/windows-walls-floors/one-way-vision", permanent: true },
  { source: "/surface-graphics/static-clings", destination: "/shop/windows-walls-floors/static-cling", permanent: true },
  { source: "/surface-graphics/wall-graphics", destination: "/shop/windows-walls-floors/wall-graphics", permanent: true },
  { source: "/surface-graphics/window-color-films", destination: "/shop/windows-walls-floors/transparent-color-film", permanent: true },
  { source: "/surface-graphics/window-decals-opaque", destination: "/shop/windows-walls-floors/opaque-window-graphics", permanent: true },
  // ── /vehicle-graphics/* ──
  { source: "/vehicle-graphics/car-graphics", destination: "/shop/vehicle-graphics-fleet/vehicle-graphics", permanent: true },
  { source: "/vehicle-graphics/dot-mc-cvor-number-decals", destination: "/shop/vehicle-graphics-fleet/dot-mc-numbers", permanent: true },
  { source: "/vehicle-graphics/fleet-branding-kits", destination: "/shop/vehicle-graphics-fleet/fleet-packages", permanent: true },
  { source: "/vehicle-graphics/fleet-inspection-compliance-kits", destination: "/shop/vehicle-graphics-fleet/inspection-compliance", permanent: true },
  { source: "/vehicle-graphics/fleet-spec-safety-labels", destination: "/shop/vehicle-graphics-fleet/spec-labels", permanent: true },
  { source: "/vehicle-graphics/fleet-unit-number-weight-decals", destination: "/shop/vehicle-graphics-fleet/unit-weight-ids", permanent: true },
  { source: "/vehicle-graphics/magnetic-vehicle-signs", destination: "/shop/vehicle-graphics-fleet/magnetic-signs", permanent: true },
  { source: "/vehicle-graphics/truck-door-logo-decals", destination: "/shop/vehicle-graphics-fleet/door-panel-graphics", permanent: true },
  { source: "/vehicle-graphics/vehicle-decals-lettering", destination: "/shop/vehicle-graphics-fleet/vehicle-decals", permanent: true },
  { source: "/vehicle-graphics/vehicle-wraps", destination: "/shop/vehicle-graphics-fleet/vehicle-wraps", permanent: true },
] as const;
