const fs = require('fs');
const path = 'C:/Users/Lilian/Desktop/web/vibe-sticker-shop/scripts/_audit-phase4.mjs';
const lines = [];

// Section 2: Duplicate detection
lines.push("");
lines.push("// --- 2. DUPLICATE DETECTION ---");
lines.push("console.log('\n\n' + '='.repeat(70));");
lines.push("console.log('  2. DUPLICATE / SIMILAR PRODUCT DETECTION');");
lines.push("console.log('='.repeat(70));");
lines.push("");
lines.push("function normalizeForComparison(str) {");
lines.push("  return str.toLowerCase().replace(/[-_]/g, ' ').replace(/prints?/g, '').replace(/standard/g, '').replace(/\s+/g, ' ').trim().split(' ').sort().join(' ');");
lines.push("}");
lines.push("");
lines.push("function slugTokens(slug) {");
lines.push("  return slug.toLowerCase().replace(/[-_]/g, ' ').split(' ').filter(Boolean).sort();");
lines.push("}");
lines.push("");
lines.push("function jaccard(a, b) {");
lines.push("  const setA = new Set(a);");
lines.push("  const setB = new Set(b);");
lines.push("  const inter = new Set([...setA].filter(x => setB.has(x)));");
lines.push("  const union = new Set([...setA, ...setB]);");
lines.push("  return inter.size / union.size;");
lines.push("}");
lines.push("");
lines.push("let dupGroupId = 0;");
lines.push("const dupGroups = [];");
lines.push("");
lines.push("categories.forEach(cat => {");
lines.push("  const items = byCategory[cat];");
lines.push("  const checked = new Set();");
lines.push("  for (let i = 0; i < items.length; i++) {");
lines.push("    if (checked.has(i)) continue;");
lines.push("    const group = [items[i]];");
lines.push("    const tokI = slugTokens(items[i].slug);");
lines.push("    const normI = normalizeForComparison(items[i].name);");
lines.push("    for (let j = i + 1; j < items.length; j++) {");
lines.push("      if (checked.has(j)) continue;");
lines.push("      const tokJ = slugTokens(items[j].slug);");
lines.push("      const normJ = normalizeForComparison(items[j].name);");
lines.push("      const slugSim = jaccard(tokI, tokJ);");
lines.push("      const nameSim = jaccard(normI.split(' '), normJ.split(' '));");
lines.push("      if (slugSim >= 0.5 || nameSim >= 0.6) {");
lines.push("        group.push(items[j]);");
lines.push("        checked.add(j);");
lines.push("      }");
lines.push("    }");
lines.push("    if (group.length > 1) {");
lines.push("      checked.add(i);");
lines.push("      dupGroupId++;");
lines.push("      dupGroups.push({ id: dupGroupId, category: cat, items: group });");
lines.push("    }");
lines.push("  }");
lines.push("});");
lines.push("");
lines.push("if (dupGroups.length === 0) {");
lines.push("  console.log('\n  No suspected duplicates found.');");
lines.push("} else {");
lines.push("  console.log('\n  Found ' + dupGroups.length + ' suspected duplicate groups:\n');");
lines.push("  dupGroups.forEach(g => {");
lines.push("    console.log('  GROUP #' + g.id + ' [' + g.category + ']');");
lines.push("    g.items.forEach(pr => {");
lines.push("      const hp = pr.pricingPresetId ? 'preset' : 'NO preset';");
lines.push("      console.log('    - ' + pr.name.padEnd(45) + ' slug=' + pr.slug.padEnd(40) + ' ' + hp);");
lines.push("    });");
lines.push("    console.log('');");
lines.push("  });");
lines.push("}");
lines.push("");
lines.push("// --- Specific canvas-prints duplicate check ---");
lines.push("console.log('  --- Specific canvas-prints duplicate check ---');");
lines.push("const canvasProducts = products.filter(pr => pr.category === 'canvas-prints');");
lines.push("const knownDupPairs = [");
lines.push("  ['canvas-prints-standard', 'canvas-standard'],");
lines.push("  ['canvas-framed', 'framed-canvas-prints'],");
lines.push("  ['canvas-gallery-wrap', 'gallery-wrap-canvas-prints'],");
lines.push("  ['canvas-panoramic', 'panoramic-canvas-prints'],");
lines.push("];");
lines.push("knownDupPairs.forEach(([a, b]) => {");
lines.push("  const prodA = canvasProducts.find(pr => pr.slug === a);");
lines.push("  const prodB = canvasProducts.find(pr => pr.slug === b);");
lines.push(`  const stA = prodA ? ('FOUND - "' + prodA.name + '"') : 'NOT FOUND';`);
lines.push(`  const stB = prodB ? ('FOUND - "' + prodB.name + '"') : 'NOT FOUND';`);
lines.push("  const verdict = (prodA && prodB) ? '** DUPLICATE PAIR **' : (prodA || prodB) ? 'Only one exists' : 'Neither exists';");
lines.push("  console.log('  ' + a.padEnd(35) + stA);");
lines.push("  console.log('  ' + b.padEnd(35) + stB);");
lines.push("  console.log('  => ' + verdict);");
lines.push("  console.log('');");
lines.push("});");

fs.appendFileSync(path, lines.join('\n') + '\n', 'utf8');
console.log('Part 2 appended: ' + lines.length + ' lines');
