const fs = require('fs');
const path = 'C:/Users/Lilian/Desktop/web/vibe-sticker-shop/scripts/_audit-phase4.mjs';
const lines = [];
lines.push("import { PrismaClient } from '../node_modules/.prisma/client/index.js';");
lines.push("const p = new PrismaClient();");
lines.push("");
lines.push("const products = await p.product.findMany({");
lines.push("  where: { isActive: true },");
lines.push("  select: {");
lines.push("    id: true, name: true, slug: true, category: true, type: true,");
lines.push("    pricingUnit: true, displayFromPrice: true, basePrice: true, minPrice: true,");
lines.push("    pricingPresetId: true, pricingConfig: true, optionsConfig: true, sortOrder: true,");
lines.push("  },");
lines.push("  orderBy: [{ category: 'asc' }, { sortOrder: 'asc' }, { name: 'asc' }],");
lines.push("});");
lines.push("");
lines.push("console.log('='.repeat(70));");
lines.push("console.log('  PHASE 4 PRODUCT AUDIT - ' + new Date().toISOString().slice(0, 10));");
lines.push("console.log('='.repeat(70));");
lines.push("console.log('Total active products: ' + products.length);");
lines.push("");
lines.push("const byCategory = {};");
lines.push("products.forEach(pr => {");
lines.push("  if (!byCategory[pr.category]) byCategory[pr.category] = [];");
lines.push("  byCategory[pr.category].push(pr);");
lines.push("});");
lines.push("const categories = Object.keys(byCategory).sort();");
lines.push("");
lines.push("// --- 1. FULL PRODUCT LIST ---");
lines.push("console.log('\n' + '='.repeat(70));");
lines.push("console.log('  1. ALL ACTIVE PRODUCTS');");
lines.push("console.log('='.repeat(70));");
lines.push("");
lines.push("categories.forEach(cat => {");
lines.push("  const items = byCategory[cat];");
lines.push("  console.log('\n-- ' + cat + ' (' + items.length + ' products) --');");
lines.push("  items.forEach((pr, i) => {");
lines.push("    const hasPreset = pr.pricingPresetId ? 'Y' : 'N';");
lines.push("    const hasOptions = (pr.optionsConfig && Object.keys(pr.optionsConfig).length > 0) ? 'Y' : 'N';");
lines.push("    const hasPricing = (pr.pricingConfig && Object.keys(pr.pricingConfig).length > 0) ? 'Y' : 'N';");
lines.push("    const unit = (pr.pricingUnit || 'none').padEnd(10);");
lines.push("    const fromPrice = pr.displayFromPrice ? ('$' + (pr.displayFromPrice / 100).toFixed(2)) : '-';");
lines.push("    console.log(");
lines.push("      '  ' + String(i + 1).padStart(3) + '. ' +");
lines.push("      pr.name.padEnd(48) +");
lines.push("      ' slug=' + pr.slug.padEnd(40) +");
lines.push("      ' unit=' + unit +");
lines.push("      ' preset=' + hasPreset +");
lines.push("      ' opts=' + hasOptions +");
lines.push("      ' pCfg=' + hasPricing +");
lines.push("      ' from=' + fromPrice");
lines.push("    );");
lines.push("  });");
lines.push("});");
fs.writeFileSync(path, lines.join('\n') + '\n', 'utf8');
console.log('Part 1 written: ' + lines.length + ' lines');
