// lib/editor/templates.js — Design template presets for business cards and flat prints

export const TEMPLATES = [
  {
    id: "modern-dark",
    name: "Modern Dark",
    category: "business-cards",
    thumbnail: null,
    canvas: {
      width: 1050, // 3.5" × 300dpi
      height: 600, // 2" × 300dpi
      background: "#111111",
    },
    elements: [
      {
        type: "text",
        text: "Your Name",
        x: 60,
        y: 180,
        fontSize: 48,
        fontFamily: "sans-serif",
        fontWeight: "bold",
        fill: "#ffffff",
      },
      {
        type: "text",
        text: "Job Title",
        x: 60,
        y: 240,
        fontSize: 24,
        fontFamily: "sans-serif",
        fill: "#999999",
      },
      {
        type: "text",
        text: "email@company.com",
        x: 60,
        y: 420,
        fontSize: 20,
        fontFamily: "sans-serif",
        fill: "#cccccc",
      },
      {
        type: "text",
        text: "(416) 555-0123",
        x: 60,
        y: 460,
        fontSize: 20,
        fontFamily: "sans-serif",
        fill: "#cccccc",
      },
      {
        type: "rect",
        x: 0,
        y: 530,
        width: 1050,
        height: 70,
        fill: "#e53e3e",
      },
    ],
  },
  {
    id: "classic-white",
    name: "Classic White",
    category: "business-cards",
    thumbnail: null,
    canvas: {
      width: 1050,
      height: 600,
      background: "#ffffff",
    },
    elements: [
      {
        type: "text",
        text: "Your Name",
        x: 525,
        y: 200,
        fontSize: 42,
        fontFamily: "serif",
        fontWeight: "bold",
        fill: "#111111",
        textAlign: "center",
      },
      {
        type: "text",
        text: "Job Title | Company",
        x: 525,
        y: 260,
        fontSize: 22,
        fontFamily: "serif",
        fill: "#666666",
        textAlign: "center",
      },
      {
        type: "line",
        x1: 375,
        y1: 310,
        x2: 675,
        y2: 310,
        stroke: "#cccccc",
        strokeWidth: 1,
      },
      {
        type: "text",
        text: "email@company.com | (416) 555-0123",
        x: 525,
        y: 360,
        fontSize: 18,
        fontFamily: "serif",
        fill: "#888888",
        textAlign: "center",
      },
    ],
  },
  {
    id: "minimal-left",
    name: "Minimal Left",
    category: "business-cards",
    thumbnail: null,
    canvas: {
      width: 1050,
      height: 600,
      background: "#fafafa",
    },
    elements: [
      {
        type: "rect",
        x: 0,
        y: 0,
        width: 8,
        height: 600,
        fill: "#2563eb",
      },
      {
        type: "text",
        text: "Your Name",
        x: 50,
        y: 200,
        fontSize: 38,
        fontFamily: "sans-serif",
        fontWeight: "bold",
        fill: "#111111",
      },
      {
        type: "text",
        text: "Job Title",
        x: 50,
        y: 252,
        fontSize: 20,
        fontFamily: "sans-serif",
        fill: "#666666",
      },
      {
        type: "text",
        text: "email@company.com",
        x: 50,
        y: 420,
        fontSize: 18,
        fontFamily: "sans-serif",
        fill: "#444444",
      },
      {
        type: "text",
        text: "(416) 555-0123",
        x: 50,
        y: 455,
        fontSize: 18,
        fontFamily: "sans-serif",
        fill: "#444444",
      },
    ],
  },
  {
    id: "bold-gradient",
    name: "Bold Gradient",
    category: "business-cards",
    thumbnail: null,
    canvas: {
      width: 1050,
      height: 600,
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    },
    elements: [
      {
        type: "text",
        text: "YOUR NAME",
        x: 525,
        y: 220,
        fontSize: 44,
        fontFamily: "sans-serif",
        fontWeight: "bold",
        fill: "#ffffff",
        textAlign: "center",
        letterSpacing: 4,
      },
      {
        type: "text",
        text: "Creative Director",
        x: 525,
        y: 290,
        fontSize: 22,
        fontFamily: "sans-serif",
        fill: "rgba(255,255,255,0.8)",
        textAlign: "center",
      },
      {
        type: "text",
        text: "hello@example.com",
        x: 525,
        y: 420,
        fontSize: 18,
        fontFamily: "sans-serif",
        fill: "rgba(255,255,255,0.7)",
        textAlign: "center",
      },
    ],
  },
];

export function getTemplate(id) {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}

export function getTemplatesByCategory(category) {
  return TEMPLATES.filter((t) => t.category === category);
}
